#
# Automagically generated by Approximatrix Simply Fortran 3.17
#
FC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\gfortran.exe"
CC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\gcc.exe"
AR="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\ar.exe"
WRC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\windres.exe"
PRJTK="C:\Program Files (x86)\Simply Fortran 3\fwin\sfprjtk.exe"
RM=rm -f

IDIR=

LDIR=


OPTFLAGS= -g

SPECIALFLAGS=$(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS=

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -J"C:/Users/mrogers/Documents/My Projects/steve/modules" 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build\fourbar.o": ".\fourbar.f"
	@echo Compiling .\fourbar.f
	@$(FC) -c -o "build\fourbar.o" $(FFLAGS) ".\fourbar.f"

clean: .SYMBOLIC
	@echo Deleting build\fourbar.o and related files
	@$(RM) "build\fourbar.o"
	@echo Deleting target.exe
	@$(RM) "target.exe"

"target.exe":  "build\fourbar.o" "build\steve.prj.target"
	@echo Generating target.exe
	@$(FC) -o "target.exe" -static "build\fourbar.o" $(LDIR) $(PRJ_LFLAGS)

all: "target.exe" .SYMBOLIC

